"""add platform and surface to shorts_usage

Revision ID: 657ba9f4d4f8
Revises: 70d943e5af25
Create Date: 2026-08-15 08:22:26.369463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657ba9f4d4f8'
down_revision: Union[str, Sequence[str], None] = '70d943e5af25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Migration-safe strategy for existing rows (documented):
    - pre-architecture rows get the explicit marker value 'UNKNOWN' for
      platform/surface via server_default. Historical platform/surface
      values are NEVER invented or fabricated.
    - if legacy rows would collide under the new logical key
      (user_id, device_id, platform, surface, usage_date), the most recently
      updated row is kept and older duplicates are removed so the unique
      constraint can be created safely. (In practice the table is empty or
      holds only idempotently-synced rows, so this is defensive.)
    - no other table is touched; Settings / Study / Monitoring tables are
      unaffected.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shorts_usage', sa.Column('platform', sa.String(length=50), server_default='UNKNOWN', nullable=False))
    op.add_column('shorts_usage', sa.Column('surface', sa.String(length=50), server_default='UNKNOWN', nullable=False))
    # ### end Alembic commands ###

    # Defensive dedupe BEFORE creating the unique constraint: keep the
    # highest-id row per logical key, remove older legacy duplicates.
    op.execute(
        """
        DELETE s1 FROM shorts_usage s1
        JOIN shorts_usage s2
          ON s1.user_id = s2.user_id
         AND s1.device_id = s2.device_id
         AND s1.platform = s2.platform
         AND s1.surface = s2.surface
         AND s1.usage_date = s2.usage_date
         AND s1.id < s2.id
        """
    )

    op.create_unique_constraint('uq_shorts_usage_user_device_platform_surface_date', 'shorts_usage', ['user_id', 'device_id', 'platform', 'surface', 'usage_date'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_shorts_usage_user_device_platform_surface_date', 'shorts_usage', type_='unique')
    op.drop_column('shorts_usage', 'surface')
    op.drop_column('shorts_usage', 'platform')
    # ### end Alembic commands ###
